
# Site settings

url: "https://lala010addict.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: 

google-tracking-id: "UA-68949592-1"

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#############
# HTML Head #
#############

author: "JieYing Peng"
lang: "en"
title: "{ JieYing Peng }"
favicon: "/img/favicon.ico"
description: "My Journey from Accountant to Front-End Developer."
keywords: "JieYing, Peng, Front-End, web, Developer, full-stack"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/jetpacktocat.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Hungry? check out my food/travel blog -> <a href="http://bunnyandporkbelly.com"> BUNNYANDPORKBELLY.com </a> "

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "jieyingpeng"

###############
# Life Events #
###############

events:
  - image: "/img/career/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/career/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "jieyingpeng010@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/lala010addict"
  - title: "instagram"
    url: "https://instagram.com/lalalala010/"
  - title: "flickr"
    url: "https://www.flickr.com/photos/lala010"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/jieyingpeng"
  - title: "twitter"
    url: "https://twitter.com/bunnynporkbelly"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'
  Project: 'project'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
